spring:
  application:
    name: BiblioTech

  datasource:
    url: jdbc:postgresql://localhost:5432/bibliotech_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mongodb:
    uri: mongodb://localhost:27017/bibliotech_mongo

springdoc:
  swagger-ui:
    path: /swagger-ui.html

security:
  jwt:
    secret-key: "4e6f756d656c6c65436c65537570657253656372657444654a574f50536563"
    expiration-ms: 86400000

server:
  port: 8080